version: '3.8'

services:
  task-manager:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "5125:5125"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5125/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.taskmanager.rule=Host(`localhost`)"
      - "traefik.http.services.taskmanager.loadbalancer.server.port=5125"
    networks:
      - taskmanager-network
    volumes:
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  taskmanager-network:
    driver: bridge

volumes:
  logs:
    driver: local