version: '3.8'

services:
  task-manager-dev:
    build: 
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "5125:5125"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - /app/__pycache__
    command: ["python", "app.py"]
    restart: unless-stopped
    networks:
      - taskmanager-dev-network

  # Optional: Add a database for future use
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=taskmanager
      - POSTGRES_USER=taskuser
      - POSTGRES_PASSWORD=taskpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskmanager-dev-network
    profiles:
      - database

  # Optional: Add Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - taskmanager-dev-network
    profiles:
      - cache

networks:
  taskmanager-dev-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
