name: Feature Branch Pipeline

on:
  push:
    branches: [ 'feature/*' ]
  pull_request:
    branches: [ 'feature/*' ]

jobs:
  feature-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run quick tests
      run: |
        python -m pytest tests/test_app.py::TestTaskCreation -v

    - name: Build Docker image
      run: |
        docker build -t task-manager-api:feature .

    - name: Test Docker image
      run: |
        docker run -d -p 5125:5125 --name feature-test task-manager-api:feature
        sleep 5
        curl -f http://localhost:5125/api || exit 1
        docker stop feature-test
        docker rm feature-test

    - name: Feature branch status
      run: |
        echo "🔧 Feature branch pipeline completed"
        echo "Branch: ${{ github.ref_name }}"
        echo "Ready for pull request to develop branch"
