name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run code quality checks
      run: |
        pip install flake8 black isort
        # Check code formatting
        black --check .
        isort --check-only .
        # Run linting
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run tests
      run: |
        python -m pytest tests/test_app.py -v --cov=app --cov-report=xml --cov-report=term-missing

    - name: Check test coverage
      run: |
        python -m pytest --cov=app --cov-fail-under=80

    - name: Build Docker image
      run: |
        docker build -t task-manager-api:pr-test .

    - name: Test Docker image
      run: |
        docker run -d -p 5125:5125 --name pr-test-container task-manager-api:pr-test
        sleep 10
        curl -f http://localhost:5125/api || exit 1
        docker stop pr-test-container
        docker rm pr-test-container

    - name: Comment PR with results
      if: always()
      uses: actions/github-script@v7
      with:
        script: |
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          
          const botComment = comments.find(comment => 
            comment.user.type === 'Bot' && comment.body.includes('## PR Check Results')
          );
          
          const testResult = '${{ job.status }}' === 'success' ? '✅ PASSED' : '❌ FAILED';
          const body = `## PR Check Results
          
          **Status:** ${testResult}
          
          **Checks Performed:**
          - ✅ Code quality (flake8, black, isort)
          - ✅ Unit tests with coverage
          - ✅ Docker build and test
          - ✅ Test coverage threshold (80%+)
          
          **Coverage:** Check the test results above for coverage details.
          
          ${testResult === '✅ PASSED' ? 'Ready for review!' : 'Please fix the issues above.'}`;
          
          if (botComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: body
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
          }
